### ISSUE TITLE
Failed to start

### ISSUE THREAD

**Issue by headfon** [guusdk/httpfileuploadcomponent#17]
Hi and thank you for your great plugin
i have problem starting this
when i start i get exception:
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - Public address(es):
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - * xxx.xxx.xxx.xxx
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - * 
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - Starting external component with endpoint http://xxx.xxx.xxx.xxx:12121
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - maxFileSize: 52428800
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - Starting repository...
[main] INFO nl.goodbytes.xmpp.xep0363.repository.AbstractFileSystemRepository - Initialized repository in: C:\Users\ADMINI~1\AppData\Local\Temp\2\xmppfileupload5004533732279233748
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - Starting webserver...
[main] INFO org.eclipse.jetty.util.log - Logging to org.slf4j.impl.SimpleLogger(org.eclipse.jetty.util.log) via org.eclipse.jetty.util.log.Slf4jLog
[main] INFO org.eclipse.jetty.util.log - jetty-1.2.0
[main] INFO org.eclipse.jetty.util.log - Started SelectChannelConnector@xxx.xxx.xxx.xxx:12121
[main] INFO nl.goodbytes.xmpp.xep0363.Launcher - Webserver started at xxx.xxx.xxx.xxx:12121
[main] ERROR nl.goodbytes.xmpp.xep0363.Launcher - An unexpected exception occurred!
org.xmpp.component.ComponentException: internal-server-error
        at org.jivesoftware.whack.ExternalComponent.connect(ExternalComponent.java:219)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:221)
        at org.jivesoftware.whack.ExternalComponentManager.addComponent(ExternalComponentManager.java:201)
        at nl.goodbytes.xmpp.xep0363.Launcher.start(Launcher.java:345)
        at nl.goodbytes.xmpp.xep0363.Launcher.main(Launcher.java:232)
[Shutdown] INFO org.eclipse.jetty.util.log - Shutdown hook executing

**Comment by guusdk** [comment]
This software is intended to connect as an External Component to an XMPP server. When it tries to connect, the server returns an error (internal-sever-error). I'm not sure why. Maybe you used the wrong password? Try looking at the log files of your server - maybe there'll be in clue in that.

**Comment by headfon** [comment]
thank you my problem refer to tmp folder
