### ISSUE TITLE
Can't get mime type of uploaded file from webserver

### ISSUE THREAD

**Issue by cesarius2** [guusdk/httpfileuploadcomponent#18]
Hi Guus,
your plugin makes image transfer with openfire a real pleasure. I was using for more than 5 years standard slow p2p transfer cause I was absolutely unaware about the XEP-363 implementation.

I got an Issue I don't really know if it is caused by the httpfileupload-plugin espcially the used Jetty-Webserver or my used windows jabber client (gajim with urlimagepreviewplugin).
The problem is that gajim can't show a preview of a picture/image sent with httpfileupload because the image preview plugin can't get the mime-type from the Jetty Webserver. So when sending an image (for example with conversations to gajim), I only get a link to the server (https://mydomain.tld:7443/http-bind/.....jpg) instead of a preview of that image.

When I try to "curl -I" the link of the Image I only get :
`HTTP/1.1 200 OK
Date: Thu, 14 Mar 2019 07:47:27 GMT
Cache-Control: max-age=31536000
ETag: 1530580421
Content-Length: 149726
Server: Jetty(9.4.12.v20180830)
`
So the mime type is missing.
I am using your plugin integrated in Openfire. So I don't know if it is caused by an old Jetty Version or may be just a configuration issue.
Thanks for the info.

**Comment by guusdk** [comment]
Related issue in Gajim's issue tracker: https://dev.gajim.org/gajim/gajim-plugins/issues/349

**Comment by guusdk** [comment]
This was fixed in v1.2.2 of this project. Version 1.1.3 of the [HTTP File Upload plugin](https://www.igniterealtime.org/projects/openfire/plugin-archive.jsp?plugin=httpfileupload) for Openfire includes this version of the library.

**Comment by guusdk** [comment]
Sadly, this fix doesn't address all issues. A followup issue was created here https://github.com/guusdk/httpfileuploadcomponent/issues/25
