### ISSUE TITLE
shharing the xmpp configuration

### ISSUE THREAD

**Issue by mkassir95** [guusdk/httpfileuploadcomponent#39]
Hello,

Can you please share the xmpp server configuration in order to run this project successfully?

**Comment by guusdk** [comment]
This is dependant on the server that you're using. Typically, you configure a 'shared secret' to be used by external components on your server, and use that for authentication. Depending on your network configuration, you will need to modify the 'announced' HTTP endpoint that is communicated by this component to your clients.
