### ISSUE TITLE
Should reconnect on xmpp server restart

### ISSUE THREAD

**Issue by Fank** [guusdk/httpfileuploadcomponent#4]

**Comment by Echse27** [comment]
I have set a cron job to start the upload service, so it will start and connect after a restart automatically.

**Comment by guusdk** [comment]
This issue puzzles me: the behavior should already be that, when a connection is lost, the component will attempt to reconnect every five seconds.

A quick test shows me that this is working. I've fired up Openfire and the component, made sure that they Openfire was showing the external component connection. Next, I stopped Openfire for about a minute, then restarted Openfire. Within moments, the component popped up in the admin console again.

Exactly how do you reproduce the error that you're reporting here?

**Comment by Fank** [comment]
I not using this anymore, but my environment is docker. So one thing that maybe can an issue that on every restart of a container, it will get a new ip. But if you can't reproduce it, close it.

**Comment by guusdk** [comment]
As I can't reproduce this, I'll close it. Feel free to reopen if it is reproducible (please specify how)
