### ISSUE TITLE
Upload Maximum 5MB

### ISSUE THREAD

**Issue by Echse27** [guusdk/httpfileuploadcomponent#5]
Hi,

there is a hardcoded maximum of uploaded files at 5 MB. 
It is possible to make this value changeable or set it fix at 30 or 50 MB?

That would be great... ;-)
Greetz...

**Comment by deleolajide** [comment]
Now that this component is available to Openfire users via the httpfileupload plugin. Can we look at making this configurable via a system property or something. That will allow us to allow an admin to set the limit from the Openfire admin web console.

**Comment by Javixu69** [comment]
@Echse27 How were you able to compile it?

**Comment by guusdk** [comment]
Version 1.1.3 allows configuration of the maximum file size using the 'maxFileSize' argument.
