### ISSUE TITLE
Encode URLS before sending to the server

### ISSUE THREAD

**Issue by lovetox** [guusdk/httpfileuploadcomponent#9]
Openfire version 4.2.3

A User of Gajim reported he gets from his server a PUT URL like this:

https://server.server/sLFKK-HZYGyjjIH1/подборка.txt

i cant upload to a URL like that with python

And some other nice people told me that URLs sent from server should be encoded

**Comment by guusdk** [comment]
You're absolutely right. This will be fixed in whatever the next version is after the current release (v1.1.3).

**Comment by cbrede** [comment]
after this fix there is already a problem if the url contains white spaces. I think the "URI.create" doesn't convert these. Could be better to use URLEncoder.


`[pool-2-thread-5] INFO nl.goodbytes.xmpp.xep0363.Component - Entity '2007@ps.team/Conversations.XJP8' obtained slot for 'Dokument 1.pdf' (71417 bytes): http://xm
[qtp231685785-17] WARN org.eclipse.jetty.util.log - HttpException(400,null,java.lang.NullPointerException)`

**Comment by guusdk** [comment]
You're right, it's failing with those spaces. I'll look into it. For the record: URLEncoder most definitely is not the right approach: that should only be used to encode query parameters.

**Comment by guusdk** [comment]
I've reworked the earlier solution, and added it to release 1.2.0 (which was done just now).
